# Forecasting configuration (skeleton)
seed: 42
base_currency: "USD"
universe:
  - SPY
  - QQQ
  - AGG
horizon_days: 20
features:
  price:
    returns_windows: [5, 20, 60]
    vol_windows: [20, 60]
    momentum_windows: [20, 60, 120]
  regimes:
    use_vix: true
cv:
  scheme: "expanding"
  n_folds: 5
  embargo_days: 5
model:
  type: "xgboost"
  params:
    n_estimators: 500
    learning_rate: 0.05
    max_depth: 4
    subsample: 0.8
    colsample_bytree: 0.8
artifacts_dir: "artifacts/forecaster"
tuning:
  enabled: true
  method: random
  n_trials: 30
  tickers: ["SPY","QQQ","AGG"]
  metric: rmse
  search_space:
    n_estimators: [300, 900]
    learning_rate: [0.03, 0.15]
    max_depth: [3, 7]
    subsample: [0.6, 0.95]
    colsample_bytree: [0.6, 0.95]
    min_child_weight: [1, 10]
    reg_lambda: [0.8, 1.8]
    reg_alpha: [0.0, 0.3]
  early_stopping_rounds: 50
  seed: 42
